location = "Uk South"
resourcegroup_name = "hub-spoke-rg"
hub-vnet-name = "hub_vnet"
spoke-vnet-name = "spoke-vnet"
spoke-vnet-name-2 = "spoke2-vnet"
username = "adminuser"
password = "P@$$w0rd1234!"